services:
###########
### API ###
###########
  api:
    container_name: dbarkowsky-capstone-api
    tty: true
    restart: on-failure
    build:
      context: ./api
    environment:
      - API_PORT=${API_PORT:-3004}
      - HOSTNAME=${HOSTNAME:-localhost}
    networks:
      - purchase-net
    ports:
      - ${API_PORT:-3004}:3004
    healthcheck:
      test: curl localhost:${API_PORT:-3004}/api/health | grep 'API running'
      interval: 20s
      timeout: 30s
      retries: 10
      start_period: 120s
networks:
  purchase-net:
    driver: "bridge"
