kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${CONTAINER_NAME}-template
labels:
  template: ${CONTAINER_NAME}-template

objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      annotations:
        app.openshift.io/route-disabled: 'false'
        openshift.io/generated-by: OpenShiftWebConsole
      name: ${CONTAINER_NAME}
      namespace: ${OPENSHIFT_PROJECT}
      labels:
        app: ${CONTAINER_NAME}
        app.kubernetes.io/component: ${CONTAINER_NAME}
        app.kubernetes.io/instance: ${CONTAINER_NAME}
        app.kubernetes.io/name: ${CONTAINER_NAME}
        app.kubernetes.io/part-of: ${APPLICATION_NAME}
        app.openshift.io/runtime: nodejs
        app.openshift.io/runtime-namespace: ${OPENSHIFT_PROJECT}
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${CONTAINER_NAME}
            from:
              kind: ImageStreamTag
              namespace: ${OPENSHIFT_PROJECT}
              name: '${CONTAINER_NAME}:latest'
            lastTriggeredImage: >-
              image-registry.openshift-image-registry.svc:5000/${OPENSHIFT_PROJECT}/${CONTAINER_NAME}@sha256:a2384bf2fd577b20d42e2d2f133f90cf47906b39c14f8060581069f4fad800c4
        - type: ConfigChange
      replicas: 1
      revisionHistoryLimit: 10
      test: false
      selector:
        app: ${CONTAINER_NAME}
        deploymentconfig: ${CONTAINER_NAME}
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${CONTAINER_NAME}
            deploymentconfig: ${CONTAINER_NAME}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: ${CONTAINER_NAME}
              image: >-
                image-registry.openshift-image-registry.svc:5000/${OPENSHIFT_PROJECT}/${CONTAINER_NAME}@sha256:a2384bf2fd577b20d42e2d2f133f90cf47906b39c14f8060581069f4fad800c4
              ports:
                - containerPort: 3004
                  protocol: TCP
              env:
                - name: API_PORT
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: API_PORT
                - name: BACKEND_URL
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: BACKEND_URL
                - name: CONTAINERIZED
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: CONTAINERIZED
                - name: FRONTEND_URL
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: FRONTEND_URL
                - name: HOSTNAME
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: HOSTNAME
                - name: MONGO_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: MONGO_DATABASE
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: MONGO_PASSWORD
                - name: MONGO_PORT
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: MONGO_PORT
                - name: MONGO_SERVICE
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: MONGO_SERVICE
                - name: MONGO_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: MONGO_USERNAME
                - name: SSO_AUTH_SERVER_URL
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: SSO_AUTH_SERVER_URL
                - name: SSO_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: SSO_CLIENT_ID
                - name: SSO_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: SSO_CLIENT_SECRET
                - name: TESTING
                  valueFrom:
                    secretKeyRef:
                      name: spr-secret
                      key: TESTING
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler

parameters:
  - description: Container Name
    displayName: Container Name
    name: CONTAINER_NAME
    required: true
  - description: OpenShift Project
    displayName: OpenShift Project
    name: OPENSHIFT_PROJECT
    required: true
  - description: Application Name
    displayName: Application Name
    name: APPLICATION_NAME
    required: true
