name: APP Linting Check

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  lint-app:
    name: Lint Frontend App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run ESLint
        run: |
          cd ./app
          npm i
          npm run lint
