# Runs API unit tests and uploads them to Code Climate
name: Code Climate API Unit Test Upload

on:
  pull_request:
    types:
      - open
      - synchronize
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/code-climate-upload.yaml"
  workflow_dispatch:

# ENV values match local development seed values only.
# Does not allow for Keycloak or GC Notify tests
env:
  TESTING: true
  API_PORT: 3004
  MONGO_PORT: 27017
  MONGO_PASSWORD: purchase-admin
  MONGO_USERNAME: purchase-admin
  MONGO_DATABASE: purchase-db
  MONGO_SERVICE: mongo
  ENVIRONMENT: local
  FRONTEND_PORT: 8080

jobs:
  cc-api-unit-tests:
    # ENVS for Code Climate
    env:
      CC_TEST_REPORTER_ID: dbec9188218937ba4399d0bb64b8a951101d15f573d6d031bb10bb47d1bf8594
      GIT_BRANCH: ${{ github.event.pull_request.head.ref }}
      GIT_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

    name: Run API Unit Tests and Upload
    runs-on: ubuntu-latest
    steps:
      # Confirm GitHub ENVs
      - name: Echo ENVs
        run: |
          echo $GIT_BRANCH
          echo $GIT_COMMIT_SHA

      # Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Import Code Climate
      - name: Import Code Climate
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

      # Allow contents of test reporter to be executed
      - name: Execute Permissions for Code Climate Binary
        run: |
          chmod +x ./cc-test-reporter

      # Notifies Code Climate of impending report
      - name: Before Build
        run: ./cc-test-reporter before-build

      # Run Unit Tests
      - name: Unit Tests
        working-directory: ./api
        run: |
          npm i
          npm run test -- --coverage ./tests/unit

      # # Use lcov to format coverage for Code Climate
      # - name: Format Test Coverage
      #   run: |
      #     ./cc-test-reporter format-coverage ./api/tests/coverage/lcov.info -t lcov --output ./api/tests/coverage/coverage.json

      # Upload coverage to Code Climate
      - name: Upload Coverage
        run: |
          ./cc-test-reporter upload-coverage -d -i ./api/tests/coverage/coverage-final.json
